fluentcms/FluentCMS

src/FluentCMS.Application/Users/CreateRoleCommand.cs
src/FluentCMS.Application/Users/CreateUserCommand.cs
src/FluentCMS.Application/Users/DeleteRoleCommand.cs
src/FluentCMS.Application/Users/EditRoleCommand.cs
src/FluentCMS.Application/Users/EditUserCommand.cs
src/FluentCMS.Application/Users/GetRolesQuery.cs
src/FluentCMS.Application/Users/GetUserByIdQuery.cs
src/FluentCMS.Application/Users/GetUsersQuery.cs
src/FluentCMS.Application/Users/RoleHandlers.cs
src/FluentCMS.Application/Users/UserHandlers.cs
src/FluentCMS.Domain/Entities/Users/Role.cs
src/FluentCMS.Domain/Entities/Users/User.cs
src/FluentCMS.Domain/Entities/Users/UserRole.cs
src/FluentCMS.Domain/Extensions.cs
src/FluentCMS.Domain/Repository/IGenericRepository.cs
src/FluentCMS.Domain/Repository/IUserRepository.cs
src/FluentCMS.Domain/Services/RoleService.cs
src/FluentCMS.Domain/Services/UserService.cs
src/FluentCMS.Repository.LiteDb.Tests/UserServiceTests.cs
src/FluentCMS.Repository.LiteDb/LiteDbGenericRepository.cs
src/FluentCMS.Repository.LiteDb/LiteDbUserRepository.cs
src/FluentCMS.Shared/Controllers/RolesController.cs
src/FluentCMS.Shared/Controllers/UsersController.cs
src/FluentCMS.Web.UI/Pages/Users/UserEdit.razor
src/FluentCMS.Web.UI/Pages/Users/UserList.razor

In this PR Role and UserRole entities added to the User aggregate.
- Select roles in create and edit user page.
- Remove related UserRoles when the user deletes.
- Add CreateManay method to IGenericRepository.
Closes #75 
Closes #80

75 add simple crud for role

---

src/FluentCMS.Web.UI/Layouts/AuthLayout.razor
src/FluentCMS.Web.UI/Layouts/PanelLayout.razor
src/FluentCMS.Web.UI/Pages/Auth/Login.razor
src/FluentCMS.Web.UI/Pages/Auth/Register.razor
src/FluentCMS.Web.UI/Pages/Auth/ResetPassword.razor
src/FluentCMS.Web.UI/Pages/Home.razor
src/FluentCMS.Web.UI/Pages/KitchenSink.razor
src/FluentCMS.Web.UI/_Imports.razor
src/FluentCMS.Web.UI/static/scss/app.css
src/FluentCMS.Web.UI/static/scss/components/_layout.scss
src/FluentCMS.Web.UI/static/tailwind.config.js
src/FluentCMS.Web.UI/wwwroot/css/app.min.css

This pull request contains new layouts and examples of authentication pages.

281 add layouts and sample auth pages

---

src/FluentCMS.Services/ContentTypeService.cs
src/FluentCMS.Web.Api/Controllers/ContentTypeController.cs

fix: implement missing APIs for `ContentType`

---

src/Tests/FluentCMS.E2eTests/Features/AppClient.feature
src/Tests/FluentCMS.E2eTests/Features/ContentTypeClient.feature
src/Tests/FluentCMS.E2eTests/Features/RoleClient.feature
src/Tests/FluentCMS.E2eTests/Features/UserClient.feature
src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAService.cs
src/Tests/FluentCMS.E2eTests/StepDefinitions/Tags/RequiresAuthenticatedAdmin.cs
src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenResponseErrorsShouldNotBeEmpty.cs
src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIAuthenticateAsync.cs

depends on #876 
user update tests were failing (Not Always)!
looks like a caching issue with DB
adding a delay between creation and modification fixes the issue!
needs more investigation
will re-open the issue if a better solution is found

912 failing update user api test

---

src/FluentCMS.Web.UI.Components/Base/BaseComponent.cs
src/FluentCMS.Web.UI.Components/Base/BaseComponentHelpers.cs

@abdolian @ParsaGachkar @TheHadiAhmadi @babakhani 
There are two type of usages:
1. You are using a component and you want to override the css name:
```
<Button CSSName="Test" Color="Color.Default">
Default
</Button>
```
2. You are inheriting from another component
```
public override string GetDefaultCSSName()
{
return "TestAmir";
}
```
As before, if you set the `Class` property, the same string will be added to the end of generated class names.

#1189 develop CSS name overriding feature

---

src/Frontend/FluentCMS.Web.UI/Default.razor.cs
src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs

- Removed `UserLogin` injection in `Default.razor.cs` and replaced it with `LayoutProcessor` to enhance modularity and service-oriented architecture.
- Updated `RenderDynamicContent` method to use the injected `LayoutProcessor` directly, improving testability and maintainability by adhering to dependency injection principles.
- Added `FluentCMS.Web.UI.DynamicRendering` namespace and registered `LayoutProcessor` as a scoped service in `ServiceExtensions.cs`, facilitating its use across the application and ensuring efficient resource management per client request.
- These changes signify a strategic shift towards better architecture practices by utilizing dependency injection, thereby making the application more modular, easier to test, and maintain.

Refactor DI and update `Default.razor.cs`

---

src/Frontend/FluentCMS.Web.UI/Default.razor.cs
src/Frontend/FluentCMS.Web.UI/DynamicRendering/LayoutProcessor.cs
src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs

- Introduced ILayoutProcessor interface in FluentCMS.Web.UI.DynamicRendering, making LayoutProcessor adhere to this new abstraction for better flexibility and future extensibility.
- Updated dependency injection in Default.razor.cs to use ILayoutProcessor, aligning with the Dependency Inversion Principle. Changed the access modifier of the LayoutProcessor property from public to private to enhance encapsulation.
- Modified service registration in ServiceExtensions.cs to register ILayoutProcessor as the service type and LayoutProcessor as the implementation, promoting decoupling and ease of future modifications.

Implement ILayoutProcessor interface

---

src/Frontend/FluentCMS.Web.ApiClients/Services/AuthManager.cs

Refactored `AuthManager` to utilize `ApiClientFactory` instead of `IHttpClientFactory`, streamlining the creation and usage of API clients within the class. The constructor now accepts an `ApiClientFactory` instance, enhancing the instantiation process of API clients. Additionally, the `Login` method has been simplified by directly using the `apiClient` to access an `Account` client for authentication, removing the need to manually create `HttpClient` and `AccountClient` instances. This change aims to simplify and improve the efficiency of the authentication process.

Refactor AuthManager for ApiClientFactory

---

src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormAutocomplete/FormAutocompleteMultiple.razor.cs
src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FileListPlugin.razor.cs

- Removed unused `System.Globalization` in `FormAutocompleteMultiple.razor.cs`.
- Adjusted and standardized brace formatting in `FileListPlugin.razor.cs`.
- Removed unnecessary spaces before braces in `FileListPlugin.razor.cs`.
- Corrected spacing around `if` statements in `FileListPlugin.razor.cs` for better readability.

Refactor and clean up Razor component files

---

README.md

Corrects and simplifies installation instructions.
- Fixes path for navigation to the main project
- remove `dotnet restore` as it implicitly run with `dotnet run`

Correct installation instruction

---

src/Backend/FluentCMS.Services/ServiceExtensions.cs
src/Backend/FluentCMS.Web.Api/Filters/ApiTokenAuthorizeFilter.cs

The `ServiceExtensions` class now registers `DefaultApiTokenProvider` instead of `JwtApiTokenProvider` for the `IApiTokenProvider` interface. The `ApiTokenAuthorizeFilter` class has a corrected method name from `Valiadate` to `Validate` for the `apiTokenProvider`'s method call.

Update token provider and fix typo in method name

---

src/Backend/FluentCMS.Services/Permissions/PermissionManager.cs
src/Backend/FluentCMS.Services/UserRoleService.cs
src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IUserRoleRepository.cs
src/Backend/Repositories/FluentCMS.Repositories.LiteDb/UserRoleRepository.cs
src/Backend/Repositories/FluentCMS.Repositories.MongoDB/UserRoleRepository.cs

Refactored user role fetching to include site-specific querying:
- PermissionManager.cs: Replaced `GetByUserId` with `GetUserRoles`.
- IUserRoleRepository.cs: Added `GetUserRoles` method, removed `GetByUserId`.
- UserRoleRepository.cs (LiteDb & MongoDB): Updated constructors, replaced `GetByUserId` with `GetUserRoles`.
Removed message handling for role and user deletions:
- UserRoleService.cs: Removed `IMessageHandler` implementations and related methods.

Refactor user role fetching and remove message handlers

---

src/Frontend/FluentCMS.Web.ApiClients/ApiClientServiceExtensions.cs
src/Frontend/FluentCMS.Web.UI/MappingProfile.cs
src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs

Replaced `UserLoginResponse` with `GetUserJwt` method in `ApiClientServiceExtensions.cs` to retrieve JWT token using `AuthenticationStateProvider`. Removed mapping configuration for `UserLoginResponse` in `MappingProfile.cs`. Removed scoped service registration and `AuthenticationStateProvider` dependency for `UserLoginResponse` in `ServiceExtensions.cs`.

Refactor authentication to use JWT token retrieval

---

src/Backend/FluentCMS.Services/LayoutService.cs
src/Backend/FluentCMS.Services/MessageHandlers/LayoutMessageHandler.cs
src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutCreatePlugin.razor.cs
src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutUpdatePlugin.razor
src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutUpdatePlugin.razor.cs

Added a new method `DeleteBySiteId` to the `ILayoutService` interface and implemented it in `LayoutService` to delete layouts by site ID. Modified `LayoutService` constructor to include `IPermissionManager` and added permission checks in `Create`, `Update`, and `Delete` methods. Updated `LayoutMessageHandler` to handle site deletions using `DeleteBySiteId`. Fixed a null reference issue in `LayoutCreatePlugin.razor.cs` and updated `LayoutUpdatePlugin.razor` to include a hidden input for layout ID and ensure `Id` is set before API calls.

Add DeleteBySiteId method and permission checks

---

src/Backend/FluentCMS.Services/LayoutService.cs
src/Backend/FluentCMS.Services/MessageHandlers/PageMessageHandler.cs
src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutListPlugin.razor
src/Shared/Exceptions/ExceptionCodes.cs

Updated ILayoutService to include ISiteRepository dependency. Modified LayoutService constructor to accept ISiteRepository. Added logic in LayoutService.Delete to prevent deleting default layouts. Implemented IMessageHandler<Layout> in PageMessageHandler. Added Handle method in PageMessageHandler for LayoutDeleted actions. Updated LayoutListPlugin.razor to hide delete button for default layouts. Added LayoutUnableToDeleteDefaultLayout exception code.

Prevent deletion of default layouts and update dependencies

---

src/Backend/FluentCMS.Web.Api/Controllers/SiteController.cs

Added code to set the `Description` and `Name` properties of the `siteTemplate` object in the `Create` method of the `SiteController` class. The `Description` defaults to an empty string if not provided.

Set Description and Name in SiteController.Create

---

src/Backend/Repositories/FluentCMS.Repositories.Caching/EntityRepository.cs
src/Backend/Repositories/FluentCMS.Repositories.Caching/SiteAssociatedRepository.cs
src/Backend/Repositories/FluentCMS.Repositories.LiteDb/SiteAssociatedRepository.cs
src/Providers/CacheProviders/FluentCMS.Providers.CacheProviders.Abstractions/ICacheProvider.cs
src/Providers/CacheProviders/FluentCMS.Providers.CacheProviders/FluentCMS.Providers.CacheProviders.csproj
src/Providers/CacheProviders/FluentCMS.Providers.CacheProviders/InMemoryCacheProvider.cs

Added XML documentation to `ICacheProvider` for better clarity. Removed `AutoMapper` package reference from the project file. Refactored `InMemoryCacheProvider` to eliminate `AutoMapper` usage. Updated `TryGetValue` method to use `string` keys consistently. Simplified `InMemoryCacheProvider` to handle cached values directly.

Refactor cache provider and remove AutoMapper dependency

---

src/Backend/FluentCMS.Entities/FluentCMS.Entities.csproj
src/Backend/FluentCMS.Services/FluentCMS.Services.csproj
src/Backend/FluentCMS.Web.Api/FluentCMS.Web.Api.csproj
src/Backend/Repositories/FluentCMS.Repositories.Caching/FluentCMS.Repositories.Caching.csproj
src/Backend/Repositories/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
src/Backend/Repositories/FluentCMS.Repositories.MongoDB/MongoDBServiceExtensions.cs
src/Frontend/FluentCMS.Web.ApiClients/FluentCMS.Web.ApiClients.csproj
src/Frontend/FluentCMS.Web.UI.Components/FluentCMS.Web.UI.Components.csproj
src/Frontend/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FluentCMS.Web.Plugins.Admin.csproj
src/Providers/ApiTokenProviders/FluentCMS.Providers.ApiTokenProviders/FluentCMS.Providers.ApiTokenProviders.csproj
src/Providers/CacheProviders/FluentCMS.Providers.CacheProviders/FluentCMS.Providers.CacheProviders.csproj
src/Providers/MessageBusProviders/FluentCMS.Providers.MessageBusProviders/FluentCMS.Providers.MessageBusProviders.csproj
src/Providers/TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders.csproj

Updated the following project files to use newer package versions:
- `FluentCMS.Entities.csproj`: `Microsoft.Extensions.Identity.Stores` to `8.0.10`
- `FluentCMS.Services.csproj`: `Microsoft.AspNetCore.Authentication.JwtBearer` to `8.0.10`
- `FluentCMS.Web.Api.csproj`: `Swashbuckle.AspNetCore` to `6.9.0`
- `FluentCMS.Repositories.Caching.csproj`: `Microsoft.Extensions.DependencyInjection.Abstractions` to `8.0.2`, `Scrutor` to `5.0.1`
- `FluentCMS.Repositories.MongoDB.csproj`: `MongoDB.Driver` to `3.0.0`
- `FluentCMS.Web.ApiClients.csproj`: `Microsoft.Extensions.DependencyInjection.Abstractions` to `8.0.2`, `Microsoft.Extensions.Http` to `8.0.1`
- `FluentCMS.Web.UI.Components.csproj`: `Microsoft.AspNetCore.Components.Web` to `8.0.10`
- `FluentCMS.Web.UI.csproj`: …

Update various package versions across multiple projects

---

src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IContentRepository.cs
src/Backend/Repositories/FluentCMS.Repositories.LiteDb/ContentRepository.cs

Updated IContentRepository to inherit from ISiteAssociatedRepository<Content> and added GetAll method. Modified ContentRepository to inherit from SiteAssociatedRepository<Content> and implemented the new GetAll method.

Refactor ContentRepository and IContentRepository

---

src/Backend/FluentCMS.Services/FileService.cs

Updated the `Rename` method in `FileService` to enhance the normalization and validation process for file names. Introduced `normalizedFileName` to store the normalized name, moved `file.Name` and `file.NormalizedName` assignments to after the existing file check, and adjusted the order of operations to ensure uniqueness before updating file properties.

Improve file name normalization and validation in Rename

---

src/Backend/FluentCMS.Services/AccountService.cs
src/Backend/FluentCMS.Web.Api/Controllers/SetupController.cs
src/Shared/Exceptions/ExceptionCodes.cs

- Added `ValidatePassword` and `ValidateUserName` methods to `IAccountService`.
- Implemented these methods in `AccountService` for password and username validation.
- Modified `SetupController` to include `IAccountService` and validate user input.
- Introduced new exception codes `UserInvalidPassword` and `UserInvalidUsername`.

Add validation methods to IAccountService and SetupController

---

src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/ModelHelpers.cs

Introduce a new case for handling FieldTypes.DATE_TIME in the ModelHelpers class. The code checks if the value in valuesDict is a DateTime object or a string. If it's a DateTime object, it returns a FieldValue<DateTime?> with the DateTime value. If it's a string, it attempts to parse it as a DateTime and returns a FieldValue<DateTime?> with the parsed value. If neither condition is met, it returns a FieldValue<DateTime?> with a null value.

Add handling for DATE_TIME in ModelHelpers

---

src/Backend/FluentCMS.Services/BlockService.cs
src/Backend/FluentCMS.Services/MessageHandlers/BlockMessageHandler.cs
src/Backend/FluentCMS.Services/MessageHandlers/PermissionMessageHandler.cs
src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteListPlugin.razor

Added a new method `Delete(IEnumerable<Guid> ids, CancellationToken cancellationToken = default)` to the `IBlockService` interface and its implementation in the `BlockService` class, enabling the deletion of multiple blocks by their IDs.
Updated `BlockMessageHandler` to implement `IMessageHandler<Site>` in addition to `IMessageHandler<SiteTemplate>`, including a new `Handle` method to delete all blocks associated with a site when a site is deleted.
Modified `PermissionMessageHandler` to handle the `SiteDeleted` action by default, ensuring no specific action is taken when a site is deleted.
Updated `SiteListPlugin.razor` to conditionally display the delete button based on the current view state, hiding the delete button if the site ID matches the current view state.

Add bulk delete to BlockService and update message handlers

---

src/FluentCMS/FluentCMS.csproj

Modified FluentCMS.csproj to set InvariantGlobalization to false. This change makes the application use the system's culture settings instead of invariant (culture-independent) settings, affecting how globalization and culture-specific operations are handled.

Change InvariantGlobalization to false in FluentCMS.csproj

---

src/FluentCMS/FluentCMS.csproj
src/FluentCMS/RepositoryServiceExtensions.cs

Removed the project reference to `FluentCMS.Repositories.EFCore.MySql` from the `FluentCMS.csproj` file. Commented out the MySQL repository service registration in `RepositoryServiceExtensions.cs`. These changes indicate that MySQL support is being removed or temporarily disabled.

Remove MySQL support from FluentCMS
