fluentcms/FluentCMS

CODE_OF_CONDUCT.md, CONTRIBUTING.md
=> #2 create contributing md file including code of conduct 

LICENSE
=> #3 Update LICENSE

CONTRIBUTING.md
=> add coding conventions section in contributing doc

src/FluentCMS.Domain/Entities/ContentTypes/ContentType.cs, src/FluentCMS.Domain/Entities/ContentTypes/ContentTypeField.cs, src/FluentCMS.Domain/Entities/ContentTypes/FieldType.cs, src/FluentCMS.Domain/Entities/ContentTypes/IFieldOptions.cs, src/FluentCMS.Domain/Extensions.cs, src/FluentCMS.Domain/FluentCMS.Domain.csproj, src/FluentCMS.Domain/Repository/IContentTypeRepository.cs, src/FluentCMS.Domain/Services/ContentTypeService.cs, src/FluentCMS.Repository.LiteDb.Tests/Entities/ContentTypes/ContentType_Tests.cs, src/FluentCMS.Repository.LiteDb/Extensions.cs, src/FluentCMS.Repository.LiteDb/LiteDbContentTypeRepository.cs
closes #57 
we will encounter deserialization issues here
@MostafaTech Any Idea?
=> Initial Content Type Implementation

src/FluentCMS.Shared/Controllers/BaseController.cs, src/FluentCMS.Shared/Controllers/UsersController.cs, src/FluentCMS.Shared/Models/ApiResult.cs, src/FluentCMS.Shared/UtilityServices/ApiClientService.cs, src/FluentCMS.Web.UI/Components/Button.razor, src/FluentCMS.Web.UI/Components/NavigationButton.razor, src/FluentCMS.Web.UI/Config/appsettings.Development.json, src/FluentCMS.Web.UI/Config/appsettings.json, src/FluentCMS.Web.UI/Layout/Sidebar.razor, src/FluentCMS.Web.UI/Pages/Users/UserEdit.razor, src/FluentCMS.Web.UI/Pages/Users/UserList.razor, src/FluentCMS.Web.UI/Pages/Weather.razor, src/FluentCMS.Web.UI/Program.cs, src/FluentCMS.Web.UI/_Imports.razor
Adding simple CRUD for users:
close #76
=> Add simple crud for users in ui

src/FluentCMS.Application/Users/DeleteUserCommand.cs, src/FluentCMS.Application/Users/EditUserCommand.cs, src/FluentCMS.Application/Users/UserHandlers.cs, src/FluentCMS.Shared/Controllers/BaseController.cs, src/FluentCMS.Shared/Controllers/UsersController.cs, src/FluentCMS.Web.UI/Pages/Users/UserEdit.razor, src/FluentCMS.Web.UI/Pages/Users/UserList.razor
Adding simple CRUD for users:
close #76
=> add create and edit user pages and delete

src/FluentCMS.Domain/Repository/IGenericRepository.cs, src/FluentCMS.Domain/Services/ContentTypeService.cs, src/FluentCMS.Domain/Services/UserService.cs, src/FluentCMS.Repository.LiteDb/LiteDbGenericRepository.cs, src/FluentCMS.Shared/ConfigurationExtensions.cs
=> set Repository GetById as nullable

src/FluentCMS.Application/Users/UserHandlers.cs, src/FluentCMS.Domain/Entities/Users/User.cs, src/FluentCMS.Domain/Repository/IUserRepository.cs, src/FluentCMS.Domain/Services/UserService.cs, src/FluentCMS.Repository.LiteDb.Tests/UserServiceTests.cs, src/FluentCMS.Web.UI/Pages/Users/UserEdit.razor
=> refactor user entity to store userRoles inside its document in litedb

src/FluentCMS.Web.UI/Layout/Sidebar.razor, src/FluentCMS.Web.UI/Pages/Counter.razor, src/FluentCMS.Web.UI/Pages/Home.razor, src/FluentCMS.Web.UI/Pages/Sites/SiteEdit.razor, src/FluentCMS.Web.UI/Pages/Sites/SiteList.razor, src/FluentCMS.Web.UI/Pages/Users/RoleEdit.razor, src/FluentCMS.Web.UI/Pages/Users/RoleList.razor, src/FluentCMS.Web.UI/Pages/Users/UserEdit.razor, src/FluentCMS.Web.UI/Pages/Users/UserList.razor, src/FluentCMS.Web.UI/Program.cs
=> put all admin pages insode /admin route

src/FluentCMS.Repositories/LiteDb/LiteDbConfig.cs, src/FluentCMS.Repositories/LiteDb/LiteDbContext.cs, src/FluentCMS.Repositories/LiteDb/LiteDbOptions.cs, src/FluentCMS.Repositories/LiteDb/LiteDbRoleRepository.cs, src/FluentCMS.Repositories/LiteDb/LiteDbServiceExtensions.cs, src/FluentCMS.Repositories/LiteDb/LiteDbUserRepository.cs, src/FluentCMS.Tests/Repositories/LiteDbAuditRepository_Tests.cs, src/FluentCMS.Tests/Repositories/LiteDbRepository_Tests.cs, src/FluentCMS.Web.UI/Config/litedb.json
- fix litedb config
- add missing user and role repositories for litedb
=> debug fix litedb configs

src/FluentCMS.Api/ApiApplicationContext.cs, src/FluentCMS.Api/FluentCMS.Api.csproj, src/FluentCMS.Api/SeedData.cs, src/FluentCMS.Entities/User.cs, src/FluentCMS.Providers/FluentCMS.Providers.csproj, src/FluentCMS.Providers/Identity/UserTokenProvider.cs, src/FluentCMS.Providers/Identity/UserTokenServiceExtensions.cs, src/FluentCMS.Repositories/Abstractions/IHostRepository.cs, src/FluentCMS.Repositories/Abstractions/IUserRepository.cs, src/FluentCMS.Repositories/LiteDb/LiteDbHostRepository.cs, src/FluentCMS.Repositories/MongoDb/MongoDbHostRepository.cs, src/FluentCMS.Repositories/MongoDb/MongoDbUserRepository.cs, src/FluentCMS.Services/HostService.cs, src/FluentCMS.Services/RoleService.cs, src/FluentCMS.Shared/IApplicationContext.cs, src/FluentCMS.Web.UI/Config/jwt.json, src/FluentCMS.Web.UI/Program.cs
=> 150 jwt token is not validate while generating in service authenticate

src/FluentCMS.Api/SeedData.cs, src/FluentCMS.Repositories/Abstractions/IHostRepository.cs, src/FluentCMS.Repositories/LiteDb/LiteDbHostRepository.cs, src/FluentCMS.Repositories/MongoDb/MongoDbHostRepository.cs, src/FluentCMS.Services/HostService.cs, src/FluentCMS.Services/RoleService.cs
=> #152 `IHostRepository` cleanup

src/FluentCMS.Services/FluentCMS.Services.csproj
=> Remove Microsoft.AspNetCore.Identity Nuget package (deprecated)

src/FluentCMS.Repositories/Abstractions/IPageRepository.cs, src/FluentCMS.Repositories/LiteDb/GenericRepository.cs, src/FluentCMS.Repositories/LiteDb/HostRepository.cs, src/FluentCMS.Repositories/LiteDb/LiteDbPageRepository.cs, src/FluentCMS.Repositories/LiteDb/PageRepository.cs, src/FluentCMS.Repositories/LiteDb/RoleRepository.cs, src/FluentCMS.Repositories/LiteDb/ServiceExtensions.cs, src/FluentCMS.Repositories/LiteDb/SiteRepository.cs, src/FluentCMS.Repositories/LiteDb/UserRepository.cs, src/FluentCMS.Repositories/MongoDB/PageRepository.cs, src/FluentCMS.Tests/Repositories/LiteDb/LiteDbAuditRepository_Tests.cs, src/FluentCMS.Tests/Repositories/LiteDb/LiteDbRepository_Tests.cs
- double check repository implementations
- check and add missing cancellation tokens
- match file naming with mongodb repositories
Closes #177
=> 177 review litedbrepositories

src/FluentCMS.Services/PageService.cs, src/FluentCMS.Shared/Exceptions/ExceptionCodes.cs, src/FluentCMS.Tests/Services/PageService_Tests.cs
- Resolve a small issue with our duplicate path checking routine.
- Implemented Business Logic Related Tests. (Will implement More!)
Closes #176
=> 176 develop tests for new page service-related rules

src/FluentCMS.Api/MappingProfiles.cs
=> update mapping profile

src/FluentCMS.Web.UI/Components/Section.razor, src/FluentCMS.Web.UI/DefaultData/layout.html, src/FluentCMS.Web.UI/Pages/Home.razor
=> 233 layout rendering engine enhancement

src/FluentCMS.Web.UI/DefaultData/layout.html, src/FluentCMS.Web.UI/Pages/Home.razor
=> 241 render engine breaks if there is a commented fluentcms tag

src/FluentCMS.Web.UI.Components/Components/ExtendedErrorBoundary.razor, src/FluentCMS.Web.UI.Components/Components/Toast/ToastProvider.razor, src/FluentCMS.Web.UI/Default.razor, src/FluentCMS.Web.UI/Default.razor.cs, src/FluentCMS.Web.UI/Services/AdminUIServiceExtensions.cs, src/FluentCMS.Web.UI/Services/ErrorMessageExtension.cs, src/FluentCMS.Web.UI/_Imports.razor
=> 783 implement error handling UI

src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor, src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
=> 787-fix-input-refactor-impacts-on-content-type

src/FluentCMS.Services/ServiceExtensions.cs, src/FluentCMS.Services/UserService.cs, src/FluentCMS.Web.Api/Controllers/AccountController.cs, src/FluentCMS.Web.Api/Models/Users/UserSendPasswordResetTokenRequest.cs, src/FluentCMS.Web.Api/Models/Users/UserValidatePasswordResetTokenRequest.cs
=> 713 password reset flow api implementation

src/FluentCMS.Services/ContentTypeService.cs, src/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
=> 823 in contenttype create api backend doesnt validate duplicate slugs

src/FluentCMS.Web.UI/Components/Version.razor, src/FluentCMS.Web.UI/Plugins/Home/HomeViewPlugin.razor, src/FluentCMS/FluentCMS.csproj
=> 827 version number should not be static in razor file

src/FluentCMS.E2E.UI/.gitignore, src/FluentCMS.E2E.UI/cypress.config.js, src/FluentCMS.E2E.UI/cypress/commands/auth.js, src/FluentCMS.E2E.UI/cypress/commands/setup.js, src/FluentCMS.E2E.UI/cypress/e2e/admin-layout.e2e.js, src/FluentCMS.E2E.UI/cypress/e2e/apps.e2e.js, src/FluentCMS.E2E.UI/cypress/e2e/content-type.e2e.js, src/FluentCMS.E2E.UI/cypress/e2e/content.e2e.js, src/FluentCMS.E2E.UI/cypress/support/commands.js, src/FluentCMS.E2E.UI/cypress/support/e2e.js, src/FluentCMS.E2E.UI/package-lock.json, src/FluentCMS.E2E.UI/package.json
[fluentcms-test-report.surge.sh](fluentcms-test-report.surge.sh)
=> feat: add html report, video and screenshot for cypress

src/FluentCMS.E2E.UI/config.js, src/FluentCMS.E2E.UI/cypress/commands/admin-layout.js, src/FluentCMS.E2E.UI/cypress/commands/apps.js, src/FluentCMS.E2E.UI/cypress/commands/auth.js, src/FluentCMS.E2E.UI/cypress/commands/content-type.js, src/FluentCMS.E2E.UI/cypress/e2e/basic.e2e.js, src/FluentCMS.E2E.UI/cypress/support/commands.js, src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Base/FieldAdvancedSettings.razor, src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
https://fluentcms-test-report.surge.sh
=> 878 fix e2e tests after adding contenttype fields

src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Text/TextAdvancedSettings.razor, src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Text/TextBasicSettings.razor
=> 883-fix-build-errors-on-textcontenttypefields

src/Tests/FluentCMS.E2eTests/Features/AppClient.feature, src/Tests/FluentCMS.E2eTests/Features/ContentTypeClient.feature, src/Tests/FluentCMS.E2eTests/Features/RoleClient.feature, src/Tests/FluentCMS.E2eTests/Features/UserClient.feature, src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAService.cs, src/Tests/FluentCMS.E2eTests/StepDefinitions/Tags/RequiresAuthenticatedAdmin.cs, src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenResponseErrorsShouldNotBeEmpty.cs, src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIAuthenticateAsync.cs
depends on #876 
deleting field test was failing (Not Always)!
looks like a caching issue with DB
adding a delay between creation and modification fixes the issue!
needs more investigation
will re-open the issue if a better solution is found
=> 917 failing delete field api test

src/FluentCMS.Web.UI.Components/Components/Card/Card.cs, src/FluentCMS.Web.UI.Components/Components/Card/Card.scss
=> #1010 Card component cleanup

src/FluentCMS.Web.UI.Components/Components/ThemeSwitcher/ThemeSwitcher.razor.js, src/FluentCMS.Web.UI.Components/Styles/App.scss, src/FluentCMS.Web.UI/App.razor, src/FluentCMS/Templates/Admin/AuthLayout.body.html, src/FluentCMS/Templates/Admin/SetupLayout.body.html, src/FluentCMS/Templates/Site/Blank/AdminLayout.body.html, src/FluentCMS/wwwroot/js/before-render.js
Using this reference for dark mode toggling https://stackoverflow.com/questions/63033412/dark-mode-flickers-a-white-background-for-a-millisecond-on-reload
=> feat: fix dark mode flickering

src/FluentCMS.E2E.UI/cypress/commands/admin-layout.js, src/FluentCMS.E2E.UI/cypress/commands/setup.js
=> fix: fix failing tests

src/FluentCMS.E2E.UI/cypress/commands/admin-layout.js, src/FluentCMS.E2E.UI/cypress/commands/content-type.js, src/FluentCMS.E2E.UI/cypress/commands/role.js, src/FluentCMS.E2E.UI/cypress/e2e/content-type.e2e.js
=> fix: fix tests after merge

src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentDetailPlugin.razor, src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentLayout.razor
and always select one content type from sidebar
=> feat: add empty state for contentManagement

src/FluentCMS.Services/UserService.cs, src/FluentCMS.Services/UserTokenProvider.cs, src/FluentCMS.Shared/IAuthContext.cs, src/FluentCMS.Web.Api/AuthContext.cs, src/FluentCMS.Web.UI/Services/AuthService.cs
https://github.com/fluentcms/FluentCMS/issues/1187#issue-2269055615
=> refactor: sync `AuthContext` and `AuthService` claims

src/Tests/FluentCMS.E2eTests/Features/AccountClient.feature, src/Tests/FluentCMS.E2eTests/Features/AccountClient.feature.cs, src/Tests/FluentCMS.E2eTests/Features/ContentTypeClient.feature.cs, src/Tests/FluentCMS.E2eTests/Features/RoleClient.feature.cs, src/Tests/FluentCMS.E2eTests/Features/SetupClient.feature, src/Tests/FluentCMS.E2eTests/Features/SetupClient.feature.cs, src/Tests/FluentCMS.E2eTests/Features/UserClient.feature.cs, src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveADto.cs, src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAService.cs, src/Tests/FluentCMS.E2eTests/StepDefinitions/Tags/RequiresAuthenticatedAdmin.cs, src/Tests/FluentCMS.E2eTests/StepDefinitions/Tags/RequiresFreshSetup.cs, src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldHaveAToken.cs, src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIAuthenticateAsync.cs, src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIChangePassword.cs, src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIRegister.cs
=> 1209 review apiclient tests

src/FluentCMS/Templates/Admin/manifest.json, src/FluentCMS/Templates/Site/Blank/manifest.json
@pournasserian I've searched entire project, `ByFileName` and `FullText` search looks like these were the only references.
=> chore: remove `Counter` from `PluginDefinitions`

src/FluentCMS.Web.Api/Controllers/ApiTokenController.cs, src/FluentCMS.Web.Api/Controllers/ContentController.cs, src/FluentCMS.Web.Api/Controllers/ContentTypeController.cs, src/FluentCMS.Web.Api/Controllers/PageController.cs, src/FluentCMS.Web.Api/Controllers/PluginController.cs, src/FluentCMS.Web.Api/Controllers/PluginDefinitionController.cs, src/FluentCMS.Web.Api/Controllers/RoleController.cs, src/FluentCMS.Web.Api/Controllers/SiteController.cs, src/FluentCMS.Web.Api/Controllers/UserController.cs
- **refactor: `UPDATE` & `DELETE` should include `READ` in `ApiTokenController`**
- **feat: add policies to `ContentController`**
- **refactor: `UPDATE` & `DELETE` should include `READ` in `ContentTypeController`**
- **feat: add policies to `PageController`**
- **feat: add policies to `PluginController`**
- **feat: add policies to `PluginDefinitionController`**
- **refactor: `UPDATE` & `DELETE` should include `READ` in `RoleController`**
- **feat: add policies to `SiteController`**
- **refactor: `UPDATE` should include `READ` in `UserController`**
- **revert: using sorting**
=> 1263 review controller policies

src/FluentCMS.Services/ApiTokenProvider.cs, src/FluentCMS.Services/ApiTokenService.cs, src/FluentCMS.Services/ServiceExtensions.cs, src/FluentCMS.Shared/IAuthContext.cs, src/FluentCMS.Web.Api/Attributes/PolicyAttribute.cs, src/FluentCMS.Web.Api/AuthContext.cs
- **feat: implement `JwtApiTokenProvider`**
- **chore: add `JwtApiTokenProvider` to `AddApplicationServices`**
- **feat: generate Jwt for `ApiToken` and store in DB**
- **fix: sync `ClaimTypes` with `ClaimTypes` we expect**
- **feat: add apikey support to `AuthContext`**
- **feat: add apikey support to `PolicyAttribute`**
=> 1261 api token generate token

src/Backend/Repositories/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
Updated the MongoDB.Driver package from version 2.26.0 to 2.27.0 in the FluentCMS.Repositories.MongoDB.csproj file to ensure compatibility and leverage new features and bug fixes.
=> Update MongoDB.Driver to 2.27.0 in FluentCMS project

src/Backend/FluentCMS.Entities/AuditableEntity.cs
- AuditableEntity now extends Entity, incorporating its properties and behaviors, including a potentially common `Id` property. This adjustment aligns with the goal of reducing redundancy and ensuring consistency in entity identification across the application. The explicit `Id` property declaration within AuditableEntity has been removed, leveraging inheritance from the Entity class to maintain a consistent identifier property framework.
=> Refactor AuditableEntity inheritance

src/Backend/FluentCMS.Services/ContentTypeService.cs, src/Backend/FluentCMS.Services/UserService.cs, src/Backend/FluentCMS.Web.Api/AuthContext.cs, src/Backend/FluentCMS.Web.Api/Extentions/SwaggerServiceExtensions.cs, src/Backend/FluentCMS.Web.Api/Models/ApiPagingResult.cs, src/Backend/FluentCMS.Web.Api/Validation/SlugAttribute.cs, src/Backend/Repositories/FluentCMS.Repositories.LiteDb/EntityRepository.cs, src/Backend/Repositories/FluentCMS.Repositories.MongoDB/AuditableEntityRepository.cs, src/Backend/Repositories/FluentCMS.Repositories.MongoDB/EntityRepository.cs, src/FluentCMS/Program.cs, src/Frontend/FluentCMS.Web.ApiClients/ApiClientException.cs, src/Frontend/FluentCMS.Web.ApiClients/ApiClientServiceExtensions.cs, src/Frontend/FluentCMS.Web.ApiClients/Services/AuthManager.cs, src/Frontend/FluentCMS.Web.UI.Components/Base/BaseComponentHelpers.cs, src/Frontend/FluentCMS.Web.UI.Components/Components/Accordion/Accordion.razor.cs, src/Frontend/FluentCMS.Web.UI.Components/Components/Accordion/Accordion.razor.scss, src/Frontend/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor.cs, src/Frontend/FluentCMS.Web.UI.Components/Components/Dropdown/Dropdown.razor.cs, src/Frontend/FluentCMS.Web.UI.Components/Components/Modal/Modal.razor.cs, src/Frontend/FluentCMS.Web.UI/PluginLoader/PluginLoader.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentListPlugin.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/FieldTypes.cs, src/Shared/Exceptions/ExceptionCodes.cs
I do some tiny imrovements on the codebase, based on sonar qube reports,
I just statically analyzed the codebase. please review it carfully.
thanks
=> Some Improvements

README.md
Corrected the spelling of "coming soon" in the list of supported databases. Fixed the spelling of "Administration Dashboard" in the roadmap section. Corrected the spelling of "Headless CMS Features" in the roadmap section.
=> Typo Corrections

src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListSettingsPlugin.razor.cs, src/Providers/TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders/ScribanTemplateRenderingProvider.cs
Updated `ContentListSettingsPlugin.razor.cs`:
- Reformatted `if` condition checking `contentTypeResponse?.Data`.
- Properly indented `Model` initialization within `if (Model is null)` block.
- Reformatted `SettingsModel` class definition to follow C# conventions.
Updated `ScribanTemplateRenderingProvider.cs`:
- Reordered `using` directives.
- Reformatted `if` condition checking `string.IsNullOrEmpty(content)`.
=> Improve code readability and formatting

src/Backend/FluentCMS.Services/UserRoleService.cs, src/Backend/Repositories/FluentCMS.Repositories.LiteDb/SiteAssociatedRepository.cs, src/Backend/Repositories/FluentCMS.Repositories.MongoDB/SiteAssociatedRepository.cs, src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormTreeSelector/FormTreeSelector.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/Components/BaseContentTypeFieldComponent.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/FieldType.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/FieldTypes.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/ModelHelpers.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FileListPlugin.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FolderBreadcrumbItemType.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/_GlobalUsings.cs
- Removed unused `using` directives in multiple files.
- Corrected `async` and `override` keyword order in `SiteAssociatedRepository.cs`.
- Added null check for `_module` in `FormTreeSelector.razor.cs`.
- Simplified boolean field assignment in `ModelHelpers.cs`.
- Added missing spaces after semicolons in `PageCreatePlugin.razor.cs` and `PageUpdatePlugin.razor.cs`.
- Updated `_GlobalUsings.cs` to include `global using FluentCMS.Web.UI.Components` and removed duplicate entry.
=> Code cleanup and minor improvements

src/Backend/FluentCMS.Services/UserRoleService.cs
The IUserRoleService interface now extends IAutoRegisterService. Updated UserRoleService constructor to include multiple dependencies. Simplified DeleteByRoleId method by removing role retrieval and permission validation steps, potentially increasing efficiency but reducing security checks.
=> Refactor UserRoleService and simplify DeleteByRoleId

src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.IFrame/IFrameEditPlugin.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.IFrame/IFrameViewPlugin.razor.cs
You can check with these values as example:
```
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d62632323.24907944!2d66.34477829206934!3d30.440524761344964!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1sfa!2s!4v1729967598975!5m2!1sfa!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
```
```
https://yesvelte.com
```
=> #2205 Fix ux of iframe edit

README.md
Added a new section "Configure the Database" to README.md, detailing how to set the database in `Program.cs` and provide connection strings in `appsettings.json`. Renumbered the steps for running the application and accessing it in the browser to include these new instructions.
=> Update README with database configuration instructions

src/Backend/FluentCMS.Services/FileService.cs, src/Backend/FluentCMS.Services/MessageHandlers/PageMessageHandler.cs, src/Backend/FluentCMS.Services/PageService.cs, src/Backend/FluentCMS.Services/SiteService.cs, src/Backend/FluentCMS.Web.Api/Controllers/SiteController.cs, src/Backend/Repositories/FluentCMS.Repositories.EFCore/DbModels/Settings.cs, src/Frontend/FluentCMS.Web.UI/Default.razor.cs, src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/MultiFile/MultiFileFieldDataTableFiles.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/MultiFile/MultiFileFieldFormFilesPicker.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentCreatePlugin.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentUpdatePlugin.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/ModelHelpers.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutListPlugin.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdatePlugin.razor.cs, src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/Components/FileManagement/FileSelectorModal.razor.cs, src/Shared/DictionaryJsonConverter.cs
Refactored various files to improve code readability and consistency:
- Swapped `using` statements in `FileService.cs`.
- Added new lines in `PageMessageHandler.cs`, `MultiFileFieldFormFilesPicker.razor.cs`, `ModelHelpers.cs`, `LayoutListPlugin.razor.cs`, and `SiteUpdatePlugin.razor.cs`.
- Adjusted formatting in `_reservedNames` list in `PageService.cs`.
- Added spaces in `if` statements in `SiteService.cs`.
- Reformatted methods in `SiteController.cs` and `ServiceExtensions.cs`.
- Removed `using` statement in `Default.razor.cs`.
- Refactored `GetFormFieldType` method in `ContentCreatePlugin.razor.cs` and `ContentUpdatePlugin.razor.cs`.
- Adjusted spaces in `try` and `catch` blocks in `MultiFileFieldDataTableFiles.razor.cs`.
- Added space in class declaration in `Settings.cs`.
- Adjusted …
=> Refactor code formatting and minor adjustments

src/Backend/FluentCMS.Services/MessageHandlers/ContentMessageHandler.cs, src/Backend/Repositories/FluentCMS.Repositories.EFCore/FluentCmsDbContext.cs, src/Backend/Repositories/FluentCMS.Repositories.EFCore/Repositories/PluginRepository.cs, src/Backend/Repositories/FluentCMS.Repositories.EFCore/Repositories/SettingsRepository.cs, src/Backend/Repositories/FluentCMS.Repositories.EFCore/Repositories/UserRepository.cs, src/Backend/Repositories/FluentCMS.Repositories.EFCore/_GlobalUsings.cs
- Added braces to lambda in `ContentMessageHandler.cs` for better readability.
- Removed unnecessary `Microsoft.EntityFrameworkCore` using directive in `FluentCmsDbContext.cs`.
- Adjusted class declaration formatting in `PluginRepository.cs`.
- Improved spacing and alignment in `SettingsRepository.cs` property initialization.
- Reordered `using` directives in `UserRepository.cs` for better organization.
- Updated `global using` directives in `_GlobalUsings.cs` for proper dependencies and organization.
=> Refactor and improve code readability and organization
